name: real_lift_image

shape_meta: &shape_meta
  obs:
    camera_0:
      shape: [3, 240, 320]
      type: rgb
    camera_1:
      shape: [3, 240, 320]
      type: rgb

    robot_eef_pos:
      shape: [3]
    robot_eef_rot:
      shape: [3]
    # robot_eef_pose:
    #   shape: [6]
    gripper_pose:
      shape: [1]

  action:
    shape: [7]

dataset_path: &dataset_path /path/to/your/dataset/dir
abs_action: &abs_action False

dataset:
  _target_: diffusion_policy.dataset.real_lift_image_dataset.RealLiftImageDataset
  shape_meta: *shape_meta
  dataset_path: *dataset_path
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  n_latency_steps: ${n_latency_steps}
  use_cache: True
  seed: 42
  val_ratio: 0.2
  max_train_episodes: null
  delta_action: False